// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bABrRhLTs",
    "aws_user_pools_web_client_id": "2vh6f45v5l86vnpu19uc65vopd"
};


export default awsmobile;
